CREATE TABLE "issacompass-hack_master_prompt" (
	"id" integer PRIMARY KEY DEFAULT 1 NOT NULL,
	"prompt" text NOT NULL,
	"createdAt" timestamp with time zone NOT NULL,
	"updatedAt" timestamp with time zone,
	CONSTRAINT "master_prompt_singleton_id_check" CHECK ("issacompass-hack_master_prompt"."id" = 1)
);
--> statement-breakpoint
CREATE TABLE "issacompass-hack_post" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "issacompass-hack_post_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(256),
	"createdAt" timestamp with time zone NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE INDEX "name_idx" ON "issacompass-hack_post" USING btree ("name");