CREATE TABLE "issacompass-hack_prompt_run" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "issacompass-hack_prompt_run_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"createdAt" timestamp with time zone NOT NULL,
	"inputClientSequence" text NOT NULL,
	"inputChatHistoryJson" jsonb NOT NULL,
	"consultantReply" text,
	"iterations" integer NOT NULL,
	"bestDelta" double precision NOT NULL,
	"bestPrompt" text NOT NULL,
	"runLogJson" jsonb NOT NULL
);
--> statement-breakpoint
ALTER TABLE "issacompass-hack_master_prompt" ALTER COLUMN "updatedAt" SET NOT NULL;