import "@/styles/globals.css";

import { type Metadata } from "next";
import { Geist } from "next/font/google";

import { SecretGate } from "@/app/_components/SecretGate";
import { TRPCReactProvider } from "@/trpc/react";

export const metadata: Metadata = {
  title: "Nike's Issa Compass Hack Panel",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const geist = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${geist.variable}`}>
      <body>
        <TRPCReactProvider>
          <SecretGate>{children}</SecretGate>
        </TRPCReactProvider>
      </body>
    </html>
  );
}
